In [ ]:
import numpy as np

#Atividade Prática: Análise de Dados no Varejo com NumPy

##Nível 1: Básico — Faturamento Semanal e Filtros

Passo 1: Crie um array unidimensional chamado pecas_vendidas contendo o histórico diário da semana: [150, 120, 90, 210, 300, 250, 180] utilizando a função np.array().

In [ ]:
pecas_vendidas = np.array([150, 120, 90, 210, 300, 250, 180])
print("Pecas vendidas:", pecas_vendidas)

Pecas vendidas: [150 120  90 210 300 250 180]


Passo 2: A gerência pediu uma estimativa rápida de faturamento. Sabendo que o preço médio de cada peça é de R$ 50,00, crie um novo array multiplicando o array original por 50. Observe como o NumPy aplica essa operação matemática a todos os elementos de uma só vez, sem a necessidade de escrever laços de repetição (operações vetorizadas).

In [ ]:
faturamento_semana = pecas_vendidas * 50
print("Faturamento diário (R$):", faturamento_semana)
print(f"Faturamento total da semana: R$ {faturamento_semana.sum():,.2f}")

Passo 3: Identifique os dias de pico. Crie uma máscara booleana para filtrar e extrair apenas os dias em que a loja vendeu estritamente mais de 200 peças (ex: pecas_vendidas > 200).

In [ ]:
mascara_pico = pecas_vendidas > 200
print("Máscara (dias > 200):", mascara_pico)
print("Vendas só nos dias de pico:", pecas_vendidas[mascara_pico])
print(f"Quantidade de dias de pico: {mascara_pico.sum()}")


Máscara (dias > 200): [False False False  True  True  True False]
Vendas só nos dias de pico: [210 300 250]
Quantidade de dias de pico: 3


##Nível 2: Intermediário — Múltiplas Filiais e Falhas de Sistema

Passo 1: Crie uma matriz 2D a partir das seguintes listas para representar as vendas:
* Loja A: [200, 220, np.nan, 250] (Houve uma falha no sistema no 3º dia, gerando um valor não-número).
* Loja B: [150, 180, 160, 190]
* Loja C: [300, 310, 290, 330]

In [ ]:
vendas_filiais = np.array([
    [200, 220, np.nan, 250], # A
    [150, 180, 160, 190],    # B
    [300, 310, 290, 330]     # C
])
print("Matriz 2D de Vendas (lojas × dias):")
print(vendas_filiais)

Matriz 2D de Vendas (lojas × dias):
[[200. 220.  nan 250.]
 [150. 180. 160. 190.]
 [300. 310. 290. 330.]]


Passo 2: Calcule o total de peças vendidas por cada loja (agregando pelas linhas). Para isso, aplique a função de soma especificando o parâmetro axis=1.

In [ ]:
total_por_loja = np.nansum(vendas_filiais, axis=1)
print("Total de peças vendidas por loja:", total_por_loja)


Total de peças vendidas por loja: [ 670.  680. 1230.]


Passo 3: A diretoria quer saber a média diária geral da rede. Como os dados reais frequentemente possuem lacunas, calcule a média utilizando a função do NumPy que ignora os valores nan. Se você usar a média normal, o resultado será contaminado e invalidará o relatório.

In [ ]:
media_nanmean = np.nanmean(vendas_filiais)
media_contaminada = np.mean(vendas_filiais)
print(f"\nMédia diária geral (ignorando NaN) = {media_nanmean:.2f}")
print(f"Média contaminada (np.mean)        = {media_contaminada:.2f}")


Média diária geral (ignorando NaN) = 234.55
Média contaminada (np.mean)        = nan


Passo 4: A meta diária de cada loja é vender 200 peças. Utilize a função np.where() para criar uma nova matriz condicional, onde os valores maiores ou iguais a 200 sejam substituídos pelo texto 'Meta Atingida', e os valores inferiores sejam substituídos por 'Abaixo'.

In [ ]:
status_meta = np.where(vendas_filiais >= 200, 'Meta Atingida', 'Abaixo')
print("\nStatus da meta por loja/dia:")
print(status_meta)


Status da meta por loja/dia:
[['Meta Atingida' 'Meta Atingida' 'Abaixo' 'Meta Atingida']
 ['Abaixo' 'Abaixo' 'Abaixo' 'Abaixo']
 ['Meta Atingida' 'Meta Atingida' 'Meta Atingida' 'Meta Atingida']]


##Nível 3: Avançado — Categorização e Destaques de Marketing

Passo 1: Para simular uma base de clientes, utilize o gerador moderno com uma semente fixa (np.random.default_rng()) para que os resultados sejam reproduzíveis. Crie uma amostra com 50 vendas sorteadas entre as opções ['Eletrônicos', 'Roupas', 'Casa'].

In [ ]:
rng = np.random.default_rng(42)
vendas_departamento = rng.choice(['Eletrônicos', 'Roupas', 'Casa'], size=50)
print("Amostra:", vendas_departamento[:10], "...")

Amostra: ['Eletrônicos' 'Casa' 'Roupas' 'Roupas' 'Roupas' 'Casa' 'Eletrônicos'
 'Casa' 'Eletrônicos' 'Eletrônicos'] ...


Passo 2: Determine o volume de vendas de cada departamento. Utilize a função np.unique habilitando o argumento return_counts=True para obter os valores únicos e suas respectivas contagens — esta é uma forma rápida de fazer o equivalente numérico de contagem de categorias.

In [ ]:
departamentos, contagens = np.unique(vendas_departamento, return_counts=True)
print("\nVolume de vendas por departamento:")
for dept, qtd in zip(departamentos, contagens):
    print(f"  {dept}: {qtd} vendas")


Volume de vendas por departamento:
  Casa: 21 vendas
  Eletrônicos: 12 vendas
  Roupas: 17 vendas


Passo 3: O time de marketing enviou um array com o faturamento de cinco campanhas simultâneas: [12000, 45000, 23000, 89000, 31000]. Identifique rapidamente a campanha campeã utilizando o método que retorna o índice (posição) do maior valor do array.

In [ ]:
faturamento_campanhas = np.array([12000, 45000, 23000, 89000, 31000])
indice_campea = np.argmax(faturamento_campanhas)
print(f"\nCampanha campeã: posição {indice_campea} com R$ {faturamento_campanhas[indice_campea]:,.2f}")

#Atividade Prática: Organização e Transformação de Dados com NumPy

##Nível 1: Básico — Geração de Sequências e Tipagem de Dados

Passo 1: Crie um array representando os 30 dias de um mês de faturamento utilizando a função np.arange(1, 31).

In [ ]:
dias_mes = np.arange(1, 31)
print("Dias do mês:", dias_mes)

Dias do mês: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


Passo 2: Simule 5 metas de vendas igualmente espaçadas entre R$ 20.000 e R$ 30.000 para uma equipe ao longo da semana utilizando a função np.linspace(20000, 30000, 5).

In [ ]:
metas = np.linspace(20000, 30000, 5)
print("\nMetas semanais:", metas)


Metas semanais: [20000. 22500. 25000. 27500. 30000.]


Passo 3: O sistema de logística exportou a contagem de estoque físico como números decimais (ex: np.array([10.5, 20.1, 30.9])). Converta este array diretamente para números inteiros utilizando o método .astype(int).

In [ ]:
estoque_decimal = np.array([10.5, 20.1, 30.9])
estoque_inteiro = estoque_decimal.astype(int)
print("\nEstoque (float):", estoque_decimal, "→ (int):", estoque_inteiro)


Estoque (float): [10.5 20.1 30.9] → (int): [10 20 30]


Passo 4: A partir do array de dias do mês criado no Passo 1, capture os últimos 5 dias e inverta a ordem (do mais recente para o mais antigo) através do fatiamento com passo negativo [::-1].

In [ ]:
ultimos_5_invertidos = dias_mes[-5:][::-1]  # também vale: dias_mes[:-6:-1]
print("\nÚltimos 5 dias invertidos:", ultimos_5_invertidos)


Últimos 5 dias invertidos: [30 29 28 27 26]


##Nível 2: Intermediário — Redimensionamento e Proteção de Dados

Passo 1: Você recebeu um array unidimensional com o total de visitas de um portal em 12 meses. Utilize o método .reshape(4, 3) para reorganizar automaticamente esses elementos em uma matriz de 4 trimestres (4 linhas e 3 colunas).

In [ ]:
visitas = np.array([1200, 1400, 1100, 1500, 1300, 1600, 1450, 1700, 1550, 1800, 1650, 1900])
visitas_t = visitas.reshape(4, 3)
print("Matriz de trimestres (4×3):")
print(visitas_t)

Matriz de trimestres (4×3):
[[1200 1400 1100]
 [1500 1300 1600]
 [1450 1700 1550]
 [1800 1650 1900]]


Passo 2: A equipe de marketing enviou os dados do primeiro semestre e a equipe comercial enviou os do segundo semestre. Combine essas duas matrizes empilhando-as verticalmente com a função np.vstack().

In [ ]:
sem1 = visitas_t[:2]   # 1º e 2º trimestres
sem2 = visitas_t[2:]   # 3º e 4º trimestres
anual = np.vstack([sem1, sem2])
print("\nEmpilhado via np.vstack (reconstrói 4×3):")
print(anual)


Empilhado via np.vstack (reconstrói 4×3):
[[1200 1400 1100]
 [1500 1300 1600]
 [1450 1700 1550]
 [1800 1650 1900]]


Passo 3: Extraia apenas o primeiro trimestre da matriz para criar um cenário de projeção no Google Colab. Para evitar a "pegadinha" onde alterar a nova fatia modifica o array original por acidente, utilize o método .copy() no momento do fatiamento.

In [ ]:
projecao = visitas_t[0].copy()
projecao[0] = 0
print("\nProjeção (copy) alterada:", projecao)
print("Original intacto?", visitas_t[0], "← sim, copia protegida")


Projeção (copy) alterada: [   0 1400 1100]
Original intacto? [1200 1400 1100] ← sim, copia protegida


Passo 4: Para exportar os dados estruturados de volta para um formato de relatório corrido, utilize o método ravel() para achatar a matriz bidimensional de volta em um array 1D.

In [ ]:
visitas_1d = visitas_t.ravel()
print("\nMatriz achatada (ravel):", visitas_1d)


Matriz achatada (ravel): [1200 1400 1100 1500 1300 1600 1450 1700 1550 1800 1650 1900]


##Nível 3: Avançado — Ranking, Broadcasting e Resolução de Sistemas

Passo 1: Você possui as seguintes pontuações de alunos em uma avaliação de pensamento computacional: np.array([85, 92, 78, 95, 88]). Em vez de apenas ordenar os valores, utilize np.argsort() para obter os índices dessa ordenação, permitindo descobrir rapidamente a posição de cada aluno no ranking geral.

In [ ]:
pontuacoes = np.array([85, 92, 78, 95, 88])
indices_ranking = np.argsort(pontuacoes)
print("Pontuações dos alunos:", pontuacoes)
print("Índices da ordenação (do menor p/ maior):", indices_ranking)
print("Notas já ordenadas:", pontuacoes[indices_ranking])

Pontuações dos alunos: [85 92 78 95 88]
Índices da ordenação (do menor p/ maior): [2 0 4 1 3]
Notas já ordenadas: [78 85 88 92 95]


Passo 2: Você possui um vetor contendo preços base em formato de linha. Insira uma nova dimensão neste vetor utilizando np.newaxis para transformá-lo estruturalmente em uma coluna. Isso prepara a matriz para cruzar e aplicar múltiplos percentuais de desconto simultaneamente via regras de broadcasting.

In [ ]:
precos = np.array([100, 200, 300])
precos_coluna = precos[:, np.newaxis]
print("\nPreços linha:", precos, "shape:", precos.shape)
print("Preços coluna:\n", precos_coluna, "shape:", precos_coluna.shape)

descontos = np.array([0.9, 0.8, 0.7])
print("\nPreços × descontos (broadcasting):\n", precos_coluna * descontos)


Preços linha: [100 200 300] shape: (3,)
Preços coluna:
 [[100]
 [200]
 [300]] shape: (3, 1)

Preços × descontos (broadcasting):
 [[ 90.  80.  70.]
 [180. 160. 140.]
 [270. 240. 210.]]


Passo 3: Descubra o custo unitário exato de dois recursos de hardware para um laboratório. O projeto A usou 2 placas robóticas e 1 sensor, custando R$ 500 no total. O projeto B usou 1 placa robótica e devolveu 1 sensor (estorno), custando R$ 100 no total. Crie a matriz de coeficientes A e o vetor de resultados b, aplicando a função np.linalg.solve(A, b) para encontrar os valores individuais das peças sem realizar o cálculo manual.

In [ ]:
A = np.array([[2, 1], [1, -1]])
b = np.array([500, 100])
custo = np.linalg.solve(A, b)
print(f"\nCusto placa robótica: R$ {custo[0]:.2f}")
print(f"Custo sensor: R$ {custo[1]:.2f}")


Custo placa robótica: R$ 200.00
Custo sensor: R$ 100.00
